http_port 8080 accel defaultsite=demo.local no-vhost

acl all src all
http_access allow all

cache_peer be1 parent 80 0 no-query originserver round-robin name=be1
cache_peer be2 parent 80 0 no-query originserver round-robin name=be2
cache_peer be3 parent 80 0 no-query originserver round-robin name=be3

cache_peer_access be1 allow all
cache_peer_access be2 allow all
cache_peer_access be3 allow all

access_log stdio:/var/log/squid/access.log
cache_log /var/log/squid/cache.log
pid_filename /var/run/squid.pid

coredump_dir /var/spool/squid
